---
sidebar: sidebar 
permalink: ONTAP/choose-ontap-910-later.html 
keywords: choose ontap target version, ontap update recommendations, identify ontap target version, recommended version, benefits and risks or ONTAP version 
summary: Conozca las ventajas y los riesgos de cada versión de ONTAP antes de actualizar su sistema de almacenamiento de ONTAP. 
---
= Compare las versiones de ONTAP para comprender los beneficios y riesgos mediante las actualizaciones de software de BlueXP 
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es muy importante comparar y comprender las ventajas y los riesgos que se asocian con la versión de destino de ONTAP antes de actualizar la versión de ONTAP para el sistema de almacenamiento.

Puede elegir la versión de destino y compararla con la versión actual para comprender las ventajas de actualizar a la versión específica en ONTAP. También puede ver los riesgos que se resolverán y los nuevos riesgos (si los hay) que surgirán al actualizar a la versión específica de ONTAP.


NOTE: Puede utilizar esta función solo si ejecuta ONTAP 9,10 o versiones posteriores.

.Pasos
. En el menú de navegación de la izquierda de BlueXP , selecciona *Estado > Actualizaciones de software*.
+
Se muestra la lista de clústeres que necesitan actualizar el software. Puede actualizar a la versión de destino recomendada o elegir otra versión.



|===
| Si... | Realice lo siguiente... 


 a| 
Desea actualizar a la versión recomendada
 a| 
. En la columna *Versión objetivo*, haga clic en *Comparar versiones* para ver los beneficios y riesgos de la actualización a la versión recomendada de ONTAP.
. Seleccione y vea información sobre los riesgos que se resolverán, el riesgo que seguirá existiendo y los nuevos riesgos que se introducirán después de la actualización.
. Opcionalmente, haga clic en *Descargar plan de actualización* para descargar una copia del plan de actualización.
. Haga clic en *Iniciar actualización* para iniciar el proceso de actualización.




 a| 
Desea elegir otra versión
 a| 
. En la columna *Versión objetivo*, haz clic en el menú desplegable y selecciona *Elegir otras versiones*.
. Seleccione la versión para ver los beneficios de la función Beneficios y Riesgos.
. Seleccione y vea información sobre los riesgos que se resolverán, el riesgo que seguirá existiendo y los nuevos riesgos que se introducirán después de la actualización.
. Opcionalmente, haga clic en *Descargar plan de actualización* para descargar una copia del plan de actualización.
. Haga clic en *Iniciar actualización* para iniciar el proceso de actualización.


|===